# syntax = docker/dockerfile:1
ARG RUBY_VERSION=3.3.6
FROM ruby:${RUBY_VERSION}-slim

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential git curl \
      libpq-dev postgresql-client \
      libvips \
    && rm -rf /var/lib/apt/lists/*

ENV RAILS_ENV=development \
    BUNDLE_PATH=/usr/local/bundle

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

CMD ["bash", "-lc", "rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0 -p 3000"]
